### ISSUE TITLE
iOS17 ，5月1日后的隐私政策，阿里云一键登录，适配新的隐私政策版本

### ISSUE THREAD

**Issue by applebest** [lyb5834/YBAliAuthSDK#1]
目前用的2.13.2的版本， 在5月1日之后，阿里云的SDK版本需要更新吗？

**Comment by lyb5834** [comment]
2.13.2 不是支持新版本的联通组件吗？还有什么要更新的

**Comment by applebest** [comment]
> 2.13.2 不支持新版本的联通组件吗？还有什么要更新的

<img width="1016" alt="image" src="https://github.com/lyb5834/YBAliAuthSDK/assets/16376401/5c0ab32c-dcad-49fd-b1fd-4051afda12e1">
需要更新版本，目前缺少隐私调用的配置文件，5.1日后，苹果审核隐私审核提交appstore会被拒绝

**Comment by applebest** [comment]
> > 2.13.2 不支持新版本的联组件通吗？还有什么要更新的
> 
> <img alt="图像" width="1016" src="https://private-user-images.githubusercontent.com/16376401/326379281-5c0ab32c-dcad-49fd-b1fd-4051afda12e1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQzODE1NTQsIm5iZiI6MTcxNDM4MTI1NCwicGF0aCI6Ii8xNjM3NjQwMS8zMjYzNzkyODEtNWMwYWIzMmMtZGNhZC00OWZkLWIxZmQtNDA1MWFmZGExMmUxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI5VDA5MDA1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZkZDUyZDU1OTQyODhiNTViOTU0ZjU0YzFmMjM0ZDgyN2Y1NzU4Y2RmMmY4MGQ4ZmQ5N2Y1N2FkNjUzMjk0YTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.F1ZE4bMWw5c7CboXeWHrPMzFstMluXW9G9x0ZeH71GA"> 需要更新版本，目前缺少隐私调用的配置文件，5.1日后，苹果审核隐私审核工作appstore会被拒绝

https://developer.apple.com/support/third-party-SDK-requirements/

**Comment by lyb5834** [comment]
好的，我知道了，我会更新SDK的

**Comment by applebest** [comment]
> 好的，我知道了，我会更新SDK的

谢谢啦👍🏻

**Comment by lyb5834** [comment]
2.13.8 已更新

**Comment by applebest** [comment]
> 2.13.8 已更新

thank you
